name: Automated tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          TEST: 'true'
          TIME_SPAN: 365
          PACKAGES: ${{ env.PACKAGES }}
          TWEET: ${{ env.TWEET }}